```{r echo=FALSE,  message=FALSE, warning=FALSE}
library(tidyverse)
library(gridExtra)
library(ggsignif)
library(ggpointdensity)
library(ggpubr)
library(ggrepel)
```


#### Is there a correlation between meassuring summary statistics (clr, ncd) for the  
#### totality of the 240 samples and those meassured in 4 sub-populations? 
x-axis: Summary statistics calculated with the totality of the 240 samples.  
y-axis: the average of the summary statistics calculated for the 4 subpopulations.  

# CLR

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Get the results from the heavy lifting done in R apocrita
from_apocrita_400 <- read.table("results/Master_CLR_combined_400.txt", header = TRUE)
from_apocrita_400$candens <- as.factor(from_apocrita_400$candens) 
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Information for ggplot anotation
gene1 <- subset(from_apocrita_400, gene == "LOC105207562")
gene2 <- subset(from_apocrita_400, gene == "LOC105200045")
gene3 <- subset(from_apocrita_400, gene == "LOC105202344")

three_genes <- rbind(gene1, gene2, gene3)

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

clr_plot_400 <- ggplot(from_apocrita_400 %>% arrange(candens), 
       aes(x = clr, y = mean_clr, colour = candens)) +
  geom_point(size = 3, alpha = 0.6) +
  # Adding linear regression line
  geom_smooth(method = "lm", se = TRUE, color = "grey") +  
  # Add names to selected points
  geom_label_repel(data = three_genes, aes(label = gene), colour = "black",
                   size= 2, nudge_x = 3, nudge_y = 6, direction = "both",
                   box.padding = 0.3, max.overlaps = 50) +
  # Change colors
  scale_colour_viridis_d(option = "D", direction = -1, 
                         name = "Candidate", labels = c("No","Yes")) + 
  #Change axis labels
  labs(y = "CLR mean 400 subpops", x = "CLR all samples") + 
  #guides(shape = FALSE) +
  theme_minimal()
clr_plot_400
```

```{r echo=FALSE, message=FALSE, warning=FALSE}

# Save the plot to the current working directory
ggsave("results/clr_plot_400.png", plot = clr_plot_400)

```

# NCD

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Get the results from the heavy lifting done in R apocrita
from_apocrita_400 <- read.table("results/Master_ncd05_combined_400.txt", header = TRUE)
from_apocrita_400$candens <- as.factor(from_apocrita_400$candens) 

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Information for ggplot anotation
gene1 <- subset(from_apocrita_400, gene == "LOC105207562")
gene2 <- subset(from_apocrita_400, gene == "LOC105200045")
gene3 <- subset(from_apocrita_400, gene == "LOC105202344")

three_genes <- rbind(gene1, gene2, gene3)

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

ncd_plot_400 <- ggplot(from_apocrita_400 %>% arrange(candens), 
       aes(x = ncd05, y = mean_ncd05, colour = candens)) +
  geom_point(size = 3, alpha = 0.6) +
  # Adding linear regression line
  geom_smooth(method = "lm", se = TRUE, color = "grey") +  
  # Add names to selected points
  geom_label_repel(data = three_genes, aes(label = gene), colour = "black",
                   size= 2, nudge_x = -0.1, nudge_y = -0.5, direction = "both",
                   box.padding = 0.3, max.overlaps = 50) +
  # Change colors
  scale_colour_viridis_d(option = "C", direction = -1, 
                         name = "Candidate", labels = c("No","Yes")) + 
  #Change axis labels
  labs(y = "NCD mean 400 subpops", x = "NCD all samples") + 
  #guides(shape = FALSE) +
  theme_minimal()
ncd_plot_400
```

```{r echo=FALSE, message=FALSE, warning=FALSE}

ggplot(from_apocrita_400 %>% subset(gene != "LOC105199771") 
                       %>% arrange(candens), 
       aes(x = ncd05, y = mean_ncd05, colour = candens)) +
  geom_point(size = 3, alpha = 0.6) +
  # Adding linear regression line
  geom_smooth(method = "lm", se = TRUE, color = "grey") +  
  # Add names to selected points
  geom_label_repel(data = three_genes, aes(label = gene), colour = "black",
                   size= 2, nudge_x = -0.02, nudge_y = -0.2, direction = "both",
                   box.padding = 0.3, max.overlaps = 50) +
  # Change colors
  scale_colour_viridis_d(option = "C", direction = -1, 
                         name = "Candidate", labels = c("No","Yes")) + 
  #Change axis labels
  labs(y = "NCD mean 400 subpops", x = "NCD all samples") + 
  #guides(shape = FALSE) +
  theme_minimal()

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

# Save the plot to the current working directory
ggsave("results/ncd_plot_400.png", plot = ncd_plot_400)

```


