```{r echo=FALSE,  message=FALSE, warning=FALSE}

library(tidyverse)
library(gridExtra)
library(ggsignif)
library(ggpointdensity)
library(ggpubr)
library(ggrepel)

```


```{r echo=TRUE, message=FALSE, warning=FALSE}
##
pop1_genes <- read.table('input/2023-08-04-ranked_by_dens-POP-1.txt', 
                         header = TRUE)
pop1_genes <- pop1_genes[, c("gene", "clr")]
names(pop1_genes) <- c("gene", "clr_pop1")
wide_pop1 <- pivot_wider(pop1_genes, names_from = "gene", values_from = "clr_pop1")

##
pop2_genes <- read.table('input/2023-08-04-ranked_by_dens-POP-2.txt', 
                         header = TRUE)
pop2_genes <- pop2_genes[, c("gene", "clr")]
names(pop2_genes) <- c("gene", "clr_pop2")
wide_pop2 <- pivot_wider(pop2_genes, names_from = "gene", values_from = "clr_pop2")

##
pop3_genes <- read.table('input/2023-08-04-ranked_by_dens-POP-3.txt', 
                         header = TRUE)
pop3_genes <- pop3_genes[, c("gene", "clr")]
names(pop3_genes) <- c("gene", "clr_pop3")
wide_pop3 <- pivot_wider(pop3_genes, names_from = "gene", values_from = "clr_pop3")

##
pop4_genes <- read.table('input/2023-08-04-ranked_by_dens-POP-4.txt', 
                         header = TRUE)
pop4_genes <- pop4_genes[, c("gene", "clr")]
names(pop4_genes) <- c("gene", "clr_pop4")
wide_pop4 <- pivot_wider(pop4_genes, names_from = "gene", values_from = "clr_pop4")

```

```{r echo=TRUE, message=FALSE, warning=FALSE}
merged_wide_clr <- bind_rows(wide_pop1, wide_pop2, wide_pop3, wide_pop4)

merged_wide_clr <- merged_wide_clr %>% select_if(~ !any(is.na(.)))

```

```{r echo=TRUE, message=FALSE, warning=FALSE}

standardized_data <- scale(merged_wide_clr)


# Perform PCA
pca_result <- prcomp(standardized_data, center = TRUE, scale. = TRUE)

# Create a data frame with PCA scores
pca_scores <- as.data.frame(pca_result$x)
#colnames(pca_scores) <- c("PC1", "PC2")  # Rename columns
```



Explained variance 

```{r echo=TRUE, message=FALSE, warning=FALSE}

explained_variance <- (pca_result$sdev^2) / sum(pca_result$sdev^2)
explained_variance

```


```{r echo=TRUE, message=FALSE, warning=FALSE}
pca_scores$row_number <- seq_len(nrow(pca_scores))

# Create a scatter plot with colored dots based on row number
ggplot(pca_scores, aes(x = PC1, y = PC2, color = as.factor(row_number))) +
  geom_point(size = 4) +
  theme_minimal()


```

